# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 17:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
