# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161223_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.Post')),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='postrelation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostRelationType'),
        ),
    ]
