# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161223_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color_class',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
